# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- deploy
variables:
  LATEX_IMAGE: leplusorg/latex

build:
  image: leplusorg/latex
  script:
    - apt update && apt install wget texlive-science -y
    - wget -r -np -R "index.html" http://debber.ulyssis.be/LaTeX_Files/
    - mv debber.ulyssis.be/LaTeX_Files/* .
    - make
  tags:
    - latex
  stage: build
  artifacts:
    paths:
      - "transmission.pdf"

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp transmission.pdf public  # copy the pdf file into the public folder
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the public folder
  only: 
    - main  # deploy the pdf only for commits made to the master branch 
